server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2ze93e667h553x8pino.mysql.rds.aliyuncs.com:3306/recycle?useUnicode=true&characterEncoding=utf-8
    username: aiden
    password: Athan173210
  web:
    resources:
      static-locations: classpath:/templates
mybatis:
  mapper-locations: classpath:/resources/mapper/*.xml
  type-aliases-package: com.jack.recycle.mapper
shiro:
  loginUrl: /loginView #未登录跳转url
  unauthorizedUrl: /unauthorized #权限不足跳转url
#单个文件上传发大小
#  spring.servlet.multipart.max-file-size=10MB
  #多个文件上传的共大小不得超过100M
#  spring.servlet.multipart.max-request-size=100MB